config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end
  end

  resources :posts do

    member do
      get "like", to: "posts#upvote"
      get "dislike", to: "posts#downvote"
    end

    collection do
      get :ecommerce
      get :travel
      get :realestate
      get :food
      get :transportation
      get :healthcare
      get :games
      get :education
      get :entertainment
      get :software
      get :finance
      get :fitness
      get :top
      get :bookmarks

    end

  end

  root 'posts#index'

  get "/:page" => "static#show"

end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_votable


# ILIKE works for postgres in production, LIKE for development
  def self.search(search)
   where("company ILIKE ?", "%#{search}%")
 end

 def to_param
   "#{id} #{company}".parameterize
 end


 scope :ecommerce, -> { where(:category => 'E-Commerce')}
 scope :travel, -> { where(:category => 'Travel')}
 scope :realestate, -> { where(:category => 'Real Estate')}
 scope :food, -> { where(:category => 'Food and Beverage')}
 scope :transportation, -> { where(:category => 'Transportation')}
 scope :finance, -> { where(:category => 'Finance')}
 scope :healthcare, -> { where(:category => 'Healthcare')}
 scope :games, -> { where(:category => 'Games')}
 scope :education, -> { where(:category => 'Education')}
 scope :entertainment, -> { where(:category => 'Entertainment')}
 scope :software, -> { where(:category => 'Other Software')}
 scope :fitness, -> { where(:category => 'Fitness')}

 scope :top, -> { where(:top => true)}













end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:index, :show, :create, :ecommerce, :travel, :realestate, :food, :transportation, :healthcare, :finance, :games, :education, :entertainment, :software, :fitness, :top]
  before_filter :admin_user, only: :new



  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order("RANDOM()").paginate(:page => params[:page], :per_page => 20)

    if params[:search]
   @posts = Post.search(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 20)

 else
   @posts = Post.all.order('RANDOM()').paginate(:page => params[:page], :per_page => 20)
 end

  end

  # GET /posts/1
  # GET /posts/1.json
  def show


    @random_post = Post.where.not(id: @post).order("RANDOM()").first



  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end






  def favorites
    @favorites = Post.all

  end



  def upvote
    @post.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @post.upvote_by current_user
    redirect_to :back
  end


  def ecommerce
    @posts = Post.ecommerce.paginate(:page => params[:page], :per_page => 20)
    render action: :index
  end

  def travel
    @posts = Post.travel.paginate(:page => params[:page], :per_page => 20)
    render action: :index
  end

  def transportation
    @posts = Post.transportation.paginate(:page => params[:page], :per_page => 20)
    render action: :index
  end

  def realestate
    @posts = Post.realestate.paginate(:page => params[:page], :per_page => 20)
    render action: :index
  end

  def food
    @posts = Post.food.paginate(:page => params[:page], :per_page => 20)
    render action: :index
  end

  def finance
    @posts = Post.finance.paginate(:page => params[:page], :per_page => 20)
    render action: :index
  end

  def healthcare
    @posts = Post.healthcare.paginate(:page => params[:page], :per_page => 20)
    render action: :index
  end

  def games
    @posts = Post.games.paginate(:page => params[:page], :per_page => 20)
    render action: :index
  end

  def education
    @posts = Post.education.paginate(:page => params[:page], :per_page => 20)
    render action: :index
  end

  def entertainment
    @posts = Post.entertainment.paginate(:page => params[:page], :per_page => 20)
    render action: :index
  end

  def software
    @posts = Post.software.paginate(:page => params[:page], :per_page => 20)
    render action: :index
  end

  def fitness
    @posts = Post.fitness.paginate(:page => params[:page], :per_page => 20)
    render action: :index
  end


  def top
    @posts = Post.top.paginate(:page => params[:page], :per_page => 20)
    render action: :index
  end

  def bookmarks
    @posts = Post.order("RANDOM()").paginate(:page => params[:page], :per_page => 20)

  end






  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:company, :description, :category, :url, :top)
    end

    def admin_user
       redirect_to(root_path) unless current_user && current_user.admin?
    end






end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def show
   render params[:page]
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>🚀 Ad Inspo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Overpass" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Work+Sans:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link href="http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css" rel="stylesheet"></link>
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet"></link>

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-128776772-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-128776772-1');
  </script>


</head>

<body>
  <header>
    <div class="wrapper clearfix">
      <div id="logo">
        <%= link_to image_tag("https://i.imgur.com/JUbkIuB.png"), root_path %>
      </div>
      <nav>

        <% if current_user && current_user.admin? %>

          <%= link_to "Submit Ad", new_post_path %>

          <% if user_signed_in? %>
            <li>
            <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
            </li>
          <% else %>
            <li>
            <%= link_to('Login', new_user_session_path)  %>
            </li>
          <% end %>






        <% else %>
        <%end %>
          <%= link_to "About", "/about" %>






      </nav>
    </div>

  </header>






  </div>

 <div class="wrapper">
  <% if current_user && current_user.admin? %>


    <p class="notice">
      <%= notice %>
    </p>
    <p class="alert">
      <%= alert %>
    </p>

    <% else %>
    <%end%>



    <%= yield %>
  </div>


<% if current_page?('/') %>

    <footer class ="site-footer">

      <!-- Begin Mailchimp Signup Form -->
      <link href="//cdn-images.mailchimp.com/embedcode/slim-10_7.css" rel="stylesheet" type="text/css">
      <style type="text/css">
      	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
      	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
      	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */


      </style>

    <!--


      <div id="mc_embed_signup">
      <form action="https://twitter.us19.list-manage.com/subscribe/post?u=ebb7d8e0cbca026c64b2782e5&amp;id=cf322cfd4d" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
          <div id="mc_embed_signup_scroll">
      	<label for="mce-EMAIL">Get Our Weekly Top 10 Ads Delivered To Your Inbox!</label>
      	<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>

-->


          <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
  <!--        <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_ebb7d8e0cbca026c64b2782e5_cf322cfd4d" tabindex="-1" value=""></div>
          <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
          </div>
      </form>
      </div>

    -->

      <!--End mc_embed_signup-->


    </footer>

    <div id="search-bar">
        <%= form_tag(posts_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Company Name" %>
          <%= submit_tag "Search", class: 'searching' %>
        <% end %>
      </div>

        </body>

        <%end%>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.select :category, ['E-Commerce','Travel', 'Real Estate', 'Food and Beverage', 'Transportation', 'Fitness', 'Finance', 'Healthcare', 'Games', 'Education', 'Entertainment', 'Other Software'], :prompt => 'Select Industry' %>
  </div>

  <div class="field">
    <%= f.label :top %><br>
    <%= f.select :top, [true, false], :prompt => 'Top of the week?' %>
  </div>


  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_headers.html.erb
<% if current_page?('/') %>


<div class = "welcome">
  Find the inspiration you're looking for.


</div>

<div class = "welcome-sub">
  Browse Facebook Ads by industry and company.
  <br>
  Get inspired and create better ads!

</div>


<%end%>


<% if current_page?('/posts/top') %>

<div class = "welcome">
Weekly Top 10
</div>

<%end%>


<% if current_page?('/posts/ecommerce') %>

<div class = "welcome">
E-Commerce Facebook Ads
</div>

<%end%>


<% if current_page?('/posts/travel') %>

<div class = "welcome">
Travel Facebook Ads
</div>

<%end%>

<% if current_page?('/posts/realestate') %>

<div class = "welcome">
Real Estate Facebook Ads
</div>

<%end%>

<% if current_page?('/posts/food') %>

<div class = "welcome">
Food & Beverage Facebook Ads
</div>

<%end%>

<% if current_page?('/posts/transportation') %>

<div class = "welcome">
Transportation Facebook Ads
</div>

<%end%>

<% if current_page?('/posts/finance') %>

<div class = "welcome">
Finance Facebook Ads
</div>

<%end%>

<% if current_page?('/posts/fitness') %>

<div class = "welcome">
Fitness Facebook Ads
</div>

<%end%>


<% if current_page?('/posts/healthcare') %>

<div class = "welcome">
Healthcare Facebook Ads
</div>

<%end%>


<% if current_page?('/posts/games') %>

<div class = "welcome">
Games Facebook Ads
</div>

<%end%>




<% if current_page?('/posts/education') %>

<div class = "welcome">
Education Facebook Ads
</div>

<%end%>


<% if current_page?('/posts/entertainment') %>

<div class = "welcome">
Entertainment Facebook Ads
</div>

<%end%>


<% if current_page?('/posts/software') %>

<div class = "welcome">
Other Software Facebook Ads
</div>

<%end%>

app/views/posts/bookmarks.html.erb
<% @posts.each do |post| %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/favorites.html.erb
hello


<div id="posts" class = "transitions-enabled">
  <% @favorites.each do |post| %>

   <div class = "box panel panel-default">

    <div class="post">
      <div class="post_image">
        <%= link_to "Like", like_post_path(post), method: :get %>

        <%= link_to (image_tag post.url), post %>
      </div>
      <div class="post_content">
        <div class="company">

        </div>

        <div class="data clearfix">
  <p class="buttons">
    <span>

      <%= post.get_likes.size %>
      <i class="fa fa-thumbs-up"></i>
    </span>
  </p>
</div>



      </div>
    </div>
  </div>

  <% end %>


</div>

app/views/posts/index.html.erb
<%= render 'headers' %>



<%#

<h1 class = "top-ten">



<%= link_to "🚀 Weekly Top 10", top_posts_path %>



<%#

</h1>

%>



<div class = "randomize">


<%= link_to "Push to randomize!", url_for(params) %>


</div>



<div id ="filters">







  <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
          Choose Industry <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to fa_icon('shopping-cart', text: "E-Commerce"), ecommerce_posts_path %></li>
          <li><%= link_to fa_icon('globe', text: "Travel"), travel_posts_path %></li>
          <li><%= link_to fa_icon('home', text: "Real Estate"), realestate_posts_path %></li>
          <li><%= link_to fa_icon('cutlery', text: "Food & Beverage"), food_posts_path %></li>
          <li><%= link_to fa_icon('car', text: "Transportation"), transportation_posts_path %></li>
          <li><%= link_to fa_icon('money', text: "Finance"), finance_posts_path %></li>
          <li><%= link_to fa_icon('bicycle', text: "Fitness"), fitness_posts_path %></li>
          <li><%= link_to fa_icon('medkit', text: "Healthcare"), healthcare_posts_path %></li>
          <li><%= link_to fa_icon('gamepad', text: "Games"), games_posts_path %></li>
          <li><%= link_to fa_icon('graduation-cap', text: "Education"), education_posts_path %></li>
          <li><%= link_to fa_icon('star', text: "Entertinment"), entertainment_posts_path %></li>
          <li><%= link_to fa_icon('cogs', text: "Other Software"), software_posts_path %></li>

          <li class="divider"></li>
        </ul>
      </div>







</div>






<div id="posts" class = "transitions-enabled">
  <% @posts.each do |post| %>

   <div class = "box panel panel-default">

    <div class="post">
      <div class="post_image">


<%#

        <%= link_to "Like", like_post_path(post), method: :get %>



        <%= link_to (image_tag post.url), post %>




      </div>
      <div class="post_content">
        <div class="company">

        </div>

        <div class="data clearfix">
  <p class="buttons">
    <span>

<%#


      <%= post.get_likes.size %>

      <%#
      <i class="fa fa-thumbs-up"></i>


      %>


    </span>
  </p>
</div>



      </div>
    </div>
  </div>

  <% end %>


</div>



<div id ="filters">







  <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
          Choose Industry <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to fa_icon('shopping-cart', text: "E-Commerce"), ecommerce_posts_path %></li>
          <li><%= link_to fa_icon('globe', text: "Travel"), travel_posts_path %></li>
          <li><%= link_to fa_icon('home', text: "Real Estate"), realestate_posts_path %></li>
          <li><%= link_to fa_icon('cutlery', text: "Food & Beverage"), food_posts_path %></li>
          <li><%= link_to fa_icon('car', text: "Transportation"), transportation_posts_path %></li>
          <li><%= link_to fa_icon('money', text: "Finance"), finance_posts_path %></li>
          <li><%= link_to fa_icon('bicycle', text: "Fitness"), fitness_posts_path %></li>
          <li><%= link_to fa_icon('medkit', text: "Healthcare"), healthcare_posts_path %></li>
          <li><%= link_to fa_icon('gamepad', text: "Games"), games_posts_path %></li>
          <li><%= link_to fa_icon('graduation-cap', text: "Education"), education_posts_path %></li>
          <li><%= link_to fa_icon('star', text: "Entertinment"), entertainment_posts_path %></li>
          <li><%= link_to fa_icon('cogs', text: "Other Software"), software_posts_path %></li>

          <li class="divider"></li>
        </ul>
      </div>







</div>





<br>
<div class = "pagination-center">


<%= will_paginate @posts, :page_links => false, :class => 'pagination' %>

</div>
<br>
<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class = "posts-show">
<div id = "posts">
<div class = "post">
  <div class = "post_image">
    <%= image_tag @post.url %>

    <% if current_user && current_user.admin? %>
    <%= link_to 'Edit', edit_post_path(@post) %>
    <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?"} %>

    <% else %>
    <% end %>
  </div>






</div>






<div class = "random_post">

<h2>
  Here's a random post!
</h2>

    <div class = "random_post_image">
      <%= link_to (image_tag @random_post.url), post_path(@random_post) %>
    </div>

</div>



</div>




</div>